;;;;;;;;;;;;;;;;;;;;;;
;; Bitrix PHP config ;;
;;;;;;;;;;;;;;;;;;;;;;

short_open_tag = On
memory_limit = 4G
max_execution_time = 300
max_input_time = 300
post_max_size = 128M
upload_max_filesize = 128M
max_input_vars = 10000

output_buffering = On
zlib.output_compression = On

expose_php = Off
cgi.fix_pathinfo = 0

date.timezone = Asia/Yerevan

;;;;;;;;;;;;;;;;;;;;;;
;; Error handling   ;;
;;;;;;;;;;;;;;;;;;;;;;
display_errors = off
display_startup_errors = On
log_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED
error_log = /proc/self/fd/2

;;;;;;;;;;;;;;;;;;;;;;
;; Sessions (INSTALL)
;;;;;;;;;;;;;;;;;;;;;;
session.save_handler = files
session.save_path = "/var/lib/php/sessions"


;;;;;;;;;;;;;;;;;;;;;;
;; Sessions         ;;
;;;;;;;;;;;;;;;;;;;;;;

;session.save_handler = redis
;session.save_path = "tcp://redis:6379?database=0"
session.gc_maxlifetime = 14400
session.cookie_httponly = On
session.use_strict_mode = On

;;;;;;;;;;;;;;;;;;;;;;
;; OPCache          ;;
;;;;;;;;;;;;;;;;;;;;;;
opcache.enable = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 100000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.fast_shutdown = 1
opcache.enable_cli = 0

;;;;;;;;;;;;;;;;;;;;;;
;; MySQL            ;;
;;;;;;;;;;;;;;;;;;;;;;
mysqli.allow_persistent = On
mysqli.max_persistent = -1
mysqli.max_links = -1

;;;;;;;;;;;;;;;;;;;;;;
;; File uploads     ;;
;;;;;;;;;;;;;;;;;;;;;;
file_uploads = On
upload_tmp_dir = /tmp

;;;;;;;;;;;;;;;;;;;;;;
;; Mail             ;;
;;;;;;;;;;;;;;;;;;;;;;
sendmail_path = /usr/sbin/sendmail -t -i
